version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.25
    #working @v1.25.0
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-160-38.compute-1.amazonaws.com
            port: '5432'
            database: debh77318lloe5
            ssl: true
            user: zilvvscehdgwsi
            password: ea07ba894a265648f0e2bdabc9cd7454a71b73d5538cf2a92df56eec61ace978
            migrations: true
